version: 2

project_name: relica
builds:
  - id: relica
    main: ./main.go
    binary: relica
    ldflags:
      - "-X github.com/opensourcerw/relica/pkg/version.Version={{.Version}}"
      - "-X github.com/opensourcerw/relica/pkg/version.Commit={{.ShortCommit}}"
      - "-X github.com/opensourcerw/relica/pkg/version.BuildDate={{.Date}}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: opensourcerw
    name: relica
  extra_files:
    - glob: scripts/Install-Relica.ps1
    - glob: LICENSE
    - glob: README.md
